import { spawnSync } from 'node:child_process';
import { copyFile, lstat, mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { ensureDir, UserError } from './common.mjs';
import { displayUnits, formatAssTimestamp, normalizeSubtitleText } from './subtitles.mjs';

function assEscape(value) {
  return normalizeSubtitleText(value, { preserveLines: true })
    .replaceAll('{', '｛')
    .replaceAll('}', '｝')
    .replaceAll('\n', '\\N');
}

export function buildBilingualAss({
  zhCues,
  enCues,
  fontName = 'Noto Sans CJK SC',
  playResX = 1920,
  playResY = 1080,
  zhFontSize = 56,
  enFontSize = 32,
}) {
  if (zhCues.length !== enCues.length) throw new UserError('Readable Chinese and English must have the same cue count for ASS');
  if (typeof fontName !== 'string' || !fontName.trim() || /[,\u0000-\u001F\u007F]/u.test(fontName)) {
    throw new UserError('ASS font name must be non-empty and cannot contain commas or control characters');
  }
  fontName = fontName.trim();
  const marginV = Math.round(playResY * 0.08);
  const header = `[Script Info]\n; Generated by subtitle-me\nTitle: subtitle-me bilingual output\nScriptType: v4.00+\nWrapStyle: 2\nScaledBorderAndShadow: yes\nYCbCr Matrix: TV.709\nPlayResX: ${playResX}\nPlayResY: ${playResY}\n\n[V4+ Styles]\nFormat: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\nStyle: Bilingual,${fontName},${zhFontSize},&H00FFFFFF,&H00FFFFFF,&H00000000,&HFF000000,0,0,0,0,100,100,0,0,1,2,0,2,80,80,${marginV},1\n\n[Events]\nFormat: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n`;
  const events = [];
  zhCues.forEach((zhCue, index) => {
    const enCue = enCues[index];
    if (Math.abs(zhCue.start - enCue.start) > 0.002 || Math.abs(zhCue.end - enCue.end) > 0.002) {
      throw new UserError(`ASS cue ${index + 1} has misaligned Chinese and English timestamps`);
    }
    const zhLines = zhCue.text.split('\n').filter((line) => line.trim());
    const enLines = enCue.text.split('\n').filter((line) => line.trim());
    if (zhLines.length !== 1) throw new UserError(`ASS cue ${index + 1} requires exactly one Chinese row`);
    if (enLines.length !== 1) throw new UserError(`ASS cue ${index + 1} requires exactly one English row`);
    if (displayUnits(zhLines[0]) > 24) throw new UserError(`ASS cue ${index + 1} exceeds 24 Chinese display units`);
    if (normalizeSubtitleText(enLines[0]).length > 84) throw new UserError(`ASS cue ${index + 1} exceeds 84 English characters`);
    const text = `{\\q2}${assEscape(zhLines[0])}\\N{\\fs${enFontSize}}${assEscape(enLines[0])}`;
    events.push(`Dialogue: 0,${formatAssTimestamp(zhCue.start)},${formatAssTimestamp(zhCue.end)},Bilingual,,0,0,0,,${text}`);
  });
  return `${header}${events.join('\n')}\n`;
}

export function ffmpegAvailable() {
  const result = spawnSync('ffmpeg', ['-version'], { encoding: 'utf8', windowsHide: true });
  return result.status === 0;
}

function filterEscape(path) {
  return resolve(path)
    .replaceAll('\\', '/')
    .replaceAll(':', '\\:')
    .replaceAll("'", "\\'");
}

async function requireRegularFile(path, label, maximumBytes = null) {
  const absolute = resolve(path);
  let info;
  try {
    info = await lstat(absolute);
  } catch (error) {
    if (error?.code === 'ENOENT') throw new UserError(`${label} does not exist: ${absolute}`);
    throw error;
  }
  if (!info.isFile()) throw new UserError(`${label} must be a regular file: ${absolute}`);
  if (maximumBytes !== null && info.size > maximumBytes) throw new UserError(`${label} exceeds the ${maximumBytes / 1024 / 1024} MiB preview limit: ${absolute}`);
  return absolute;
}

async function rejectNonRegularOutput(path) {
  const absolute = resolve(path);
  try {
    const info = await lstat(absolute);
    if (!info.isFile()) throw new UserError(`ASS preview output must be a regular file when it already exists: ${absolute}`);
  } catch (error) {
    if (error?.code !== 'ENOENT') throw error;
  }
  return absolute;
}

export function buildPreviewArgs({ assPath, outputPath, videoPath, at = 5, playResX = 1920, playResY = 1080 }) {
  const previewAt = Number(at);
  if (!Number.isFinite(previewAt) || previewAt < 0) throw new UserError('--at must be a non-negative number');
  const inputArgs = videoPath
    ? ['-i', resolve(videoPath)]
    : ['-f', 'lavfi', '-i', `color=c=#18202b:s=${playResX}x${playResY}:d=${Math.max(previewAt + 1, 1)}`];
  const filter = `ass=filename='${filterEscape(assPath)}'`;
  return ['-hide_banner', '-loglevel', 'error', ...inputArgs, '-ss', String(previewAt), '-vf', filter, '-frames:v', '1', '-y', resolve(outputPath)];
}

export async function renderAssPreview({ assPath, outputPath, videoPath, at = 5, playResX = 1920, playResY = 1080 }) {
  const safeAssInput = await requireRegularFile(assPath, 'ASS preview input', 64 * 1024 * 1024);
  const safeVideoInput = videoPath ? await requireRegularFile(videoPath, 'ASS preview video') : undefined;
  const safeOutput = await rejectNonRegularOutput(outputPath);
  if (!ffmpegAvailable()) {
    throw new UserError('FFMPEG_REQUIRED: ASS preview needs FFmpeg. Ask the user before offering installation steps.', 2);
  }
  await ensureDir(dirname(safeOutput));
  const temporary = await mkdtemp(join(tmpdir(), 'subtitle-me-ass-'));
  try {
    const safeAssPath = join(temporary, 'subtitle.ass');
    await copyFile(safeAssInput, safeAssPath);
    const args = buildPreviewArgs({ assPath: safeAssPath, outputPath: safeOutput, videoPath: safeVideoInput, at, playResX, playResY });
    const result = spawnSync('ffmpeg', args, { encoding: 'utf8', windowsHide: true });
    if (result.status !== 0) throw new UserError(`FFmpeg preview failed:\n${result.stderr || result.stdout}`);
    return { outputPath: safeOutput, command: ['ffmpeg', ...args] };
  } finally {
    await rm(temporary, { recursive: true, force: true });
  }
}
